In [1]:
import numpy as np
import LineCreator as L

## generated_points

In [2]:
## This should return a array ([0,1/2],[0,1])
a,b=L.generated_points_f()
a.shape
b.shape

(1, 2)

(2, 1)

In [3]:
a
b

array([[-0.87288981,  0.66332352]])

array([[-0.38879972],
       [ 0.87122895]])

## input_matrix_f

In [4]:
## This should return column vector [2,4]
test_points=np.array((2,4))
test_output=L.input_matrix_f(test_points)
test_output.shape
test_output

(2, 1)

array([[2],
       [4]])

## Lin_weight_vector_f

In [5]:
## This should return (1/2,1/2) for the pseudo_inverse
test_input_matrix=L.input_matrix_f(np.array([1,1]))
L.Lin_weight_vector_f(test_input_matrix,np.array([1,0]))

array([ 0.5])

## constant_vector_f

In [6]:
## This should return 0.5
test_constant_vector=np.arange(2)
L.constant_vector_f(test_constant_vector)

0.5

## appended_input_matrix_f

In [7]:
## This should return [1,1],[1,2]
test_appended_input_matrix=np.array([1,2])
test_output_matrix=L.appended_input_matrix_f(test_appended_input_matrix)
test_output_matrix

array([[ 1.,  1.],
       [ 1.,  2.]])

## LinReg_weight_vector_f

In [8]:
## This should return [[2,-1],[-1,1]] for the pseudoinverse
test_column_vector=np.array([1,1])
L.LinReg_weight_vector_f(test_output_matrix,test_column_vector)

array([ 1.,  0.])

## nonlinear_input_matrix_f

In [9]:
## This should return [4,4] in column form
L.nonlinear_input_matrix_f(np.array([2,2]))

array([[4],
       [4]])

## Testing syntax

In [10]:
## If this returns a 1 by 2 array
np.random.rand(1,2)

array([[ 0.04859554,  0.65178502]])

In [11]:
np.sin(np.array((5,4)))

array([-0.95892427, -0.7568025 ])

In [12]:
np.pi

3.141592653589793

In [13]:
np.arange(2)

array([0, 1])

In [14]:
np.dot(np.array([1,1]),np.array([1,1]))

2