In [1]:
import WeightDecay as W
import numpy as np

## datapoints_f

In [2]:
## This should return the in dataset 
path='/home/benson/Desktop/Code/CS156/Weight-Decay-Regularization/in.dta'
datapoints,result_vector=W.datapoints_f(path)
datapoints
result_vector

array([[-0.77947021,  0.83822138],
       [ 0.15563491,  0.89537743],
       [-0.0599077 , -0.71777995],
       [ 0.20759636,  0.75893338],
       [-0.19598312, -0.37548716],
       [ 0.58848947, -0.84255381],
       [ 0.00719859, -0.5483165 ],
       [ 0.73883852, -0.60339369],
       [ 0.70464808, -0.02042005],
       [ 0.96992666,  0.6413712 ],
       [ 0.43543099,  0.74477254],
       [-0.84425822,  0.74235423],
       [ 0.59142471, -0.54602118],
       [-0.06909312,  0.03766   ],
       [-0.95154865, -0.73305502],
       [-0.12988138,  0.75676096],
       [-0.49534647, -0.56627908],
       [-0.90399413,  0.5092215 ],
       [ 0.29235128,  0.16089015],
       [ 0.64798552, -0.77933769],
       [ 0.37595574,  0.07820309],
       [ 0.24588993,  0.00451467],
       [-0.45719155,  0.42390461],
       [-0.44127876,  0.70571892],
       [ 0.50744669,  0.75872586],
       [-0.13258381, -0.58178837],
       [-0.44749067,  0.19576364],
       [ 0.81658199, -0.45449182],
       [-0.94422408,

array([ 1.,  1.,  1.,  1., -1.,  1., -1.,  1.,  1., -1., -1.,  1.,  1.,
       -1., -1.,  1., -1.,  1., -1.,  1., -1., -1.,  1.,  1., -1., -1.,
        1.,  1.,  1., -1.,  1., -1.,  1., -1.,  1.])

## input_matrix_f

In [3]:
## This should return the transformed datapoints
input_matrix=W.input_matrix_f(datapoints)
input_matrix

array([[  1.00000000e+00,  -7.79470210e-01,   8.38221380e-01,
          6.07573808e-01,   7.02615082e-01,  -6.53368595e-01,
          1.61769159e+00,   5.87511700e-02],
       [  1.00000000e+00,   1.55634910e-01,   8.95377430e-01,
          2.42222252e-02,   8.01700742e-01,   1.39351986e-01,
          7.39742520e-01,   1.05101234e+00],
       [  1.00000000e+00,  -5.99077030e-02,  -7.17779950e-01,
          3.58893288e-03,   5.15208057e-01,   4.30005481e-02,
          6.57872247e-01,   7.77687653e-01],
       [  1.00000000e+00,   2.07596360e-01,   7.58933380e-01,
          4.30962487e-02,   5.75979875e-01,   1.57551807e-01,
          5.51337020e-01,   9.66529740e-01],
       [  1.00000000e+00,  -1.95983120e-01,  -3.75487160e-01,
          3.84093833e-02,   1.40990607e-01,   7.35891451e-02,
          1.79504040e-01,   5.71470280e-01],
       [  1.00000000e+00,   5.88489470e-01,  -8.42553810e-01,
          3.46319856e-01,   7.09896923e-01,  -4.95834045e-01,
          1.43104328e+00,   2.5

In [4]:
## Debugging
transpose=datapoints.T
transpose[0]

array([-0.77947021,  0.15563491, -0.0599077 ,  0.20759636, -0.19598312,
        0.58848947,  0.00719859,  0.73883852,  0.70464808,  0.96992666,
        0.43543099, -0.84425822,  0.59142471, -0.06909312, -0.95154865,
       -0.12988138, -0.49534647, -0.90399413,  0.29235128,  0.64798552,
        0.37595574,  0.24588993, -0.45719155, -0.44127876,  0.50744669,
       -0.13258381, -0.44749067,  0.81658199, -0.94422408,  0.46265533,
        0.88311642,  1.001605  ,  0.60370095, -0.14858757,  0.01165216])

In [5]:
## Testing np.abs
test_abs=np.array([1,-2,4,-21.3])
np.abs(test_abs)

array([  1. ,   2. ,   4. ,  21.3])

## squared_error_f

In [6]:
test_weight_vector=np.array([1,1])
test_datapoints=np.arange(0,4).reshape(2,2)
test_result_vector=np.array([1,0])

In [8]:
## This should return 12.5
W.squared_error_f(test_weight_vector,test_datapoints,test_result_vector)

12.5