In [1]:
import numpy as np
from sympy import init_session
#init_printing()
from sympy.interactive import printing
printing.init_printing(use_latex=True)

## Testing gradient function

In [2]:
import GradDescent as G

In [3]:
## This should return [2,2]
a=np.array([1,1],dtype=np.float128)
G.gradient(*a)

array([ 13.69543,  7.8607945], dtype=float128)

## Testing error function

In [4]:
G.error(*a)

3.930397231877100995

## Finally: gradient descent

In [5]:
state,count=G.grad_descent()

In [6]:
count
state

array([ 0.04473629,  0.023958714], dtype=float128)

In [7]:
G.coord_descent()

array([ 0.13981379], dtype=float128)

## Testing different Sympy evaluations

#### subs

In [8]:
from sympy.abc import x,y

In [9]:
expr=x**2

In [10]:
a=np.array([1],dtype=np.float128)
type(expr.subs(x,a))

sympy.core.numbers.Float

In [11]:
#%timeit expr.subs(x,np.array([2]))

#### lambdify

In [12]:
from sympy import lambdify

In [13]:
f=lambdify(x,expr,"numpy")

In [14]:
#%timeit f(np.array([2,4]))

## Testing syntax

In [15]:
## testing sympy basics
from sympy.functions import exp
from sympy import *

In [16]:
N(exp(1))

In [17]:
## testing correct symbolic calculation of gradient
part_x,part_y=G.test_gradient()
part_x
part_y

In [18]:
## broadcasting the lambdified function
px=lambdify([x,y],part_x)
px

<function numpy.<lambda>>

In [19]:
px(*np.array([1,1]))

In [20]:
## Testing correct dtype to get 1e-14
test_comparison=np.array([.00000000000001],dtype=np.float128)

In [21]:
ab=test_comparison<1e-13
ab[0]

True

In [22]:
## Testing numpy setting 
test_single=np.array([1])
test_single=5
type(test_single)

int

In [23]:
test_type=np.array([1.2423224],dtype=np.float128)
type(test_type[0])

numpy.float128

In [24]:
test_mult=0.05*np.array([1.34123341231114],dtype=np.float128)

In [25]:
test_mult

array([ 0.067061671], dtype=float128)

In [26]:
test_mult[0]=5

In [27]:
type(test_mult[0])

numpy.float128

In [28]:
test_gradient_accuracy=np.array([1.231123,2.412124],dtype=np.float128)

In [29]:
afd,jdafk=G.gradient(*test_gradient_accuracy)

In [30]:
type(jdafk)

numpy.float128

In [31]:
sd=np.array([jdafk,1])

In [32]:
sd

array([ 324.28551,  1.0], dtype=float128)