In [1]:
import LinearSetup as L

In [6]:
dataset=L.random_points(100)
dataset

array([[ 0.67221933, -0.79518481,  0.44893678,  0.16265565, -0.53511479,
         0.21513537,  0.22914826, -0.38292243,  0.74205412,  0.92385876,
        -0.07981455, -0.48542793, -0.51682387, -0.80605965, -0.8518727 ,
        -0.38085498,  0.15593418, -0.73914592, -0.70389366,  0.00336007,
         0.86393467, -0.61182749,  0.42961203, -0.88083028,  0.3656494 ,
         0.00993767, -0.78432467, -0.99354249,  0.01820762, -0.31578495,
        -0.45565883, -0.99709114,  0.30234069,  0.10593656,  0.05023557,
        -0.57019074,  0.23092568, -0.07915936,  0.39993871, -0.88632563,
         0.05803012,  0.17008321,  0.85439799,  0.86516465,  0.30973133,
        -0.69231305, -0.31549136, -0.4310557 , -0.16884111,  0.84058225,
        -0.45352789, -0.09025161, -0.64746045,  0.29599601, -0.60495789,
         0.20092124,  0.91179444,  0.95179094,  0.46789454,  0.26129239,
         0.90818399,  0.58536718,  0.12055736,  0.88003281, -0.89592116,
         0.29661007,  0.43450032, -0.12876904,  0.6

In [3]:
random_line=L.random_line()

In [4]:
final_result=L.points_assigner(dataset,random_line)
final_result

array([ 0.,  0.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  0.,  1.,  0.,  1.,
        0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  0.,  1.,  0.,
        1.,  1.,  0.,  1.,  1.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,  1.,
        1.,  1.,  0.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,
        0.,  0.,  1.,  0.,  1.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  0.,
        0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  0.,
        0.,  1.,  0.,  1.,  1.,  1.,  1.,  0.,  1.,  0.,  1.,  1.,  1.,
        0.,  1.,  1.,  0.,  1.,  0.,  1.,  0.,  1.])

In [5]:
## Testing random line numpy array behavior 
b = random_line(0)
m = random_line(1) - b
b-m
b/m*np.ones(3)
np.arange(2)-np.array(1)

array([-0.76901443])

NameError: name 'np' is not defined

In [ ]:
import matplotlib.pyplot as plt
domain=np.linspace(-1,1,10)
plt.plot(domain,random_line(domain))
plt.show()

In [ ]:
import pickle
with open("LinReg.pickle", "wb") as f:
    pickle.dump([final_result,b,m],f)

## Testing syntax

In [ ]:
import numpy as np

In [ ]:
asff=np.random.random(size=(2,3))

In [ ]:
asx,asy=asff.shape

In [ ]:
## Testing how numpy integrates bool types. 
# Apparantly it changes them to 1 or 0
asff[1][0]=True

asff

In [ ]:
asff[0:1,:]

In [15]:
def ():
    return 5

SyntaxError: invalid syntax (<ipython-input-15-5dca01244862>, line 1)