In [1]:
import numpy as np
import LinearSetup as L
import Nonlinear as N

## 8

In [2]:
E_in_list=np.zeros(1000)

In [3]:
for i in range(1000):
    random_points=L.random_points_f(1000)
    noisy_vector=N.noisy_vector_f(random_points)
    input_matrix=L.input_matrix_f(random_points)
    LR_weight_vector=L.LinReg_weight_vector_f(input_matrix,noisy_vector)
    reg_line=L.reg_line_f(LR_weight_vector)
    ## Collection
    E_in_list[i]=L.frequency_of_mismatch_f(reg_line,random_points,noisy_vector)

In [4]:
E_in_list.mean()

0.50076399999999999

## 9

In [5]:
E_out_list=np.zeros(1000)
nonlinear_weight_vector=np.zeros((1000,6))

In [6]:
for i in range(1000):
    random_points2=L.random_points_f(1000)
    higher_input_matrix=N.higher_input_matrix_f(random_points2)
#    print(higher_input_matrix.shape)
    noisy_vector2=N.noisy_vector_f(random_points2)
 #   print(noisy_vector2.shape)
    LR_weight_vector2=L.LinReg_weight_vector_f(higher_input_matrix,noisy_vector2)
#    print(LR_weight_vector2.shape)
    ## Collection
    E_out_list[i]=N.higher_classification_error_f(LR_weight_vector2,higher_input_matrix,noisy_vector2)
    nonlinear_weight_vector[i]=LR_weight_vector2

In [20]:
E_out_list.mean()
nonlinear_weight_vector.mean(axis=2)

0.615533

IndexError: tuple index out of range

## Testing

In [8]:
## Testing numpy list expansion
def nonlinear_function(x1,x2):
    return x1**2+x2**2>10

In [9]:
test_expand=np.arange(6).reshape((2,3))
test_expand

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
nonlinear_function(*test_expand)

array([False,  True,  True], dtype=bool)

In [11]:
import random as r

In [12]:
## Testing random sample
r.sample(range(1,1000),10)

[314, 237, 917, 710, 637, 938, 757, 264, 147, 919]

In [13]:
## Testing fancy indexing output
test_fancy=np.arange(5)
replace=test_fancy[[1,3]]

In [14]:
test_replace=np.zeros(5)
np.put(test_replace,[1,3],replace)
test_replace

array([ 0.,  1.,  0.,  3.,  0.])

In [15]:
test_expand[0]*test_expand[1]

array([ 0,  4, 10])

In [16]:
test_expand.shape

(2, 3)